name: CI - Automation Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Start Selenium Grid
        run: docker compose up -d

      - name: Wait for Grid
        run: sleep 10

      - name: Run tests
        env:
          REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}
          SELENIUM_GRID_URL: http://localhost:4444
        run: mvn clean test

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: target/allure-results